### ISSUE TITLE
emails to @codetahoe.com

### ISSUE THREAD

**Issue by Zenprechaun** [CodeTahoe/CT300#3]
Hi Rush, I have sent you a couple of emails today and am wondering if you have received them and if emails at the following addresses are being received, as I haven't received a response from anyone;

To:
Rush Tehrani: rush@codetahoe.com
Cc:
Jameson Stafford: j@codetahoe.com
Tim Olesnavage: tim@codetahoe.com

**Comment by TimOlesnavage** [comment]
I’ve gotten all of them (as long as they are sent to my gmail….still can’t send you anything from elevate blue email).

Tim Olesnavage
timolesnavage@gmail.com

**Comment by rushtehrani** [comment]
@Zenprechaun those are the correct emails.  I replied to you this morning but got a delivery failed message back from your email server.  Today's lectures are posted in the [CT300](https://github.com/CodeTahoe/CT300/tree/master/lectures)  repo if you want to review and catch up.

**Comment by Zenprechaun** [comment]
good, I'm glad you got the emails and I'll review the lecture notes.
